//Sign
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const IS_LOGGED = "IS_LOGGED";
//Packs
export const FETCH_PACKS = "FETCH_PACKS";
export const SELECT_PACK = "SELECT_PACK";
export const SELECTED_PACK = "SELECTED_PACK";
export const SELECT_THEME = "SELECT_THEME";
export const ESTIMATE_COST = "ESTIMATE_COST";
//Inventory
export const FETCH_INVENTORY = "FETCH_INVENTORY";
//Orders
export const FETCH_ORDERS = "FETCH_ORDERS";
export const SELECT_ORDER = "SELECT_ORDER";
//Proofs
export const FETCH_PROOFS = "FETCH_PROOFS";
export const SELECT_PROOF = "SELECT_PROOF";
export const ADD_PRODUCT_COMMENTS = "ADD_PRODUCT_COMMENTS";
export const FETCH_PRODUCT_COMMENTS = "FETCH_PRODUCT_COMMENTS";

//Staff
export const FETCH_STAFF = "FETCH_STAFF";
export const FILTER_BY_DATE_STAFF = "FILTER_BY_DATE_STAFF";

//Bag
export const FETCH_ORDER = "FETCH_ORDER";
export const ADD_TO_BAG = "ADD_TO_BAG";
export const DEL_FROM_BAG = "DEL_FROM_BAG";
export const CREATE_ORDER = "CREATE_ORDER";
export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const ESTIMATED_COST = "ESTIMATED_COST";

//notification
export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION";
export const SET_NOTIFICATION_READED = "SET_NOTIFICATION_READED";

//profile
export const LOAD_PROFILE = "LOAD_PROFILE";
export const SAVE_PROFILE = "SAVE_PROFILE";
export const UPDATE_BILLING_INFO = "UPDATE_BILLING_INFO";

//company
export const LOAD_COMPANY = "LOAD_COMPANY";
export const SAVE_COMPANY = "SAVE_COMPANY";

//sections
export const FETCH_SECTIONS = "FETCH_SECTIONS";
export const SELECT_SECTION = "SELECT_SECTION";
export const UPDATE_SECTION = "UPDATE_SECTION";


//tours
export const FETCH_TOURS = "FETCH_TOURS";
export const SELECT_TOUR = "SELECT_TOUR";
export const DELETE_TOUR = "DELETE_TOUR";
export const UPDATE_TOUR = "UPDATE_TOUR";
export const ADD_TOUR = "ADD_TOUR";
export const CHANGE_TOUR_PROGRAM = "CHANGE_TOUR_PROGRAM";
export const CHANGE_TOUR_COMMENT = "CHANGE_TOUR_COMMENT";
export const ADD_TOUR_COMMENT = "ADD_TOUR_COMMENT";
export const DELETE_TOUR_COMMENT = "DELETE_TOUR_COMMENT";




//attractions
export const FETCH_ATTRACTIONS = "FETCH_ATTRACTIONS";
export const SELECT_ATTRACTION = "SELECT_ATTRACTION";
export const DELETE_ATTRACTION = "DELETE_ATTRACTION";
export const UPDATE_ATTRACTION = "UPDATE_ATTRACTION";
export const ADD_ATTRACTION = "ADD_ATTRACTION";
export const CHANGE_ATTRACTION_PROGRAM = "CHANGE_ATTRACTION_PROGRAM";
export const ADD_ATTRACTION_COMMENT = "ADD_ATTRACTION_COMMENT";
export const DELETE_ATTRACTION_COMMENT = "DELETE_ATTRACTION_COMMENT";
export const CHANGE_ATTRACTION_COMMENT = "CHANGE_ATTRACTION_COMMENT";

//models
export const FETCH_MODELS = "FETCH_MODELS";
export const SELECT_MODEL = "SELECT_MODEL";
export const DELETE_MODEL = "DELETE_MODEL";
export const UPDATE_MODEL = "UPDATE_MODEL";
export const ADD_MODEL = "ADD_MODEL";
export const CHANGE_MODEL_PROGRAM = "CHANGE_MODEL_PROGRAM";
export const ADD_MODEL_COMMENT = "ADD_MODEL_COMMENT";
export const DELETE_MODEL_COMMENT = "DELETE_MODEL_COMMENT";
export const CHANGE_MODEL_COMMENT = "CHANGE_MODEL_COMMENT";
export const UPDATE_MODEL_TAGS = "UPDATE_MODEL_TAGS";

//categories
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

//language
export const SET_LANG_EN = "SET_LANG_EN";
export const SET_LANG_ES = "SET_LANG_ES";

//rating
export const SET_USER_SERVICE_RATE = "SET_USER_SERVICE_RATE;"

// blog
export const FETCH_POSTS = "FETCH_POSTS";
export const SELECT_POST = "SELECT_POST";
export const FETCH_BLOG_CATEGORIES = "FETCH_BLOG_CATEGORIES";

//tags
export const FETCH_TAGS = "FETCH_TAGS";

// cart
export const TOGGLE_OPEN = "TOGGLE_OPEN";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPY_CART = "EMPY_CART";



