const strings = {
    en:{
      welcome:"Welcome to Viñales Traveler",
      fistp:"A Tour Guide Company for you to enjoy your visit to the fullest.",
      secondp:"Reliables, locals and very experienced, we will guide you through, so you won’t miss a thing.",
      thirdp:"We will show you the good places, we will fill your time with amazing adventures.",
      button : " Discover It Now",
      english: "English",
      spanish: "Spanish",
      Tours: "Tours",
      Attractions: "Attractions",
      Lodgings: "Lodgings",
      About: "About",
      Contact: "Contact",
      Account: "Account",
      ViewOffers: "View Offers",
      ViewOffer: "View Offer",
      AllLodgings: "All Lodgings",
      AboutUs: "About Us",
      AboutUsText: `Viñales Traveler is a Tour Company based in Pinar del Río, Cuba. Committed to show our province’s beauties and realities from inside, we will cover all of Pinar del Río Province’s tourist places via a wide range of customized ecological and sightseeing tours to natural, historical and cultural sites. Also providing tips and guide for lodgings, restaurants, and all sort of activities and attraction, through our catalog of Viñales's tourism businesses. 
      <br/>With over ten years of experience in the Tourism Industry as tour guides among other jobs, our very professional local staff have gathered all the necessary knowledge and expertise to fulfill our customers’ expectations.`,
       ContactUs: "Contact Us",
      ContactUsText: "Viñales Traveler is at your service 24/7. Feel free to contact us by this means, we will be happy to attend your requests.",
      FirstName: "First name",
      Name: "Name",
      ContactEmail: "Contact email",
      Subject: "Subject",
      Message: "Message",
      Send: "Send",
      GoForIt: "Go For It",
      BookIt: "Book It",
      SortBy: "Sort by:",
      None: "None",
      Filter: "Filter:",
      Ascending: "Ascending",
      Descending: "Descending",
      Comments: "Comments",
      Price: "Price",
      Duration: "Duration",
      Program: "Program",
      Languages: "Languages",
      Category: "Category",
      Sections: "Sections",
      Categories: "Categories",
      Services: "Services",
      PickUpTime: "Pick up time",
      Guide: "Guide",
      Caracteristics: "Caracteristics",
      Capacity: "Capacity",      
      Images: "Images",
      Videos: "Videos",
      Location: "Location",
      AnythigElse: "Anythig else...",
      NumberOfPeople: "Number of People",
      Date: "Date",
      ViewAll: "View All",
      LodgingsBookingText: "Fill the following form and send us the reservation data for {0}. We'll get back tu you in no time.",
      SignAccount: "Sign in to your account" ,
      AccountEmailAddress: "Account email address",
      Password: "Password",
      RememberMe: "Remember me",
      ForgotPassword: "Forgot your password?",
      CreateAccount: "Create an account",
      LastName: "Last name",
      EmailAddress: "Email address",
      BusinessName: "Business name",
      SignUp: "Sign up",
      SignUpFacebook: "Sign up with Facebook",
      SignIn: "Sign In",
      SignInFacebook: "Login with Facebook",
      AlreadyMember: "Already a member?",
      DontAccount: "Don't have an account?",
      RepeatPassword: "Repeat password",
      MyBusinesses: "My Businesses",
      Cancel: "Cancel",
      ToLeaveComment: "To rate or leave a comment",
      SignInYou: "Sign In",
      FacebookLoginFailed: "Facebook Login Error",
      WrontCredentials: "Wront credentials",
      AddComment: "Add Comment",
      EditComment: "Edit Comment",
      Edit: "Edit",
      Delete: "Delete",
      Sending: "Sending...",
      NewAttraction: "New Attraction",
      NewLodging: "NewLodging",
      Add: "Add",
      See: "See",
      Save: "Save",
      PriceSpecifics: "Price specifications",
      FullDescription: "Full description",
      GeneralDescription: "General description",
      AddFormText: "Fill the content to display for the new {0}",
      EditFormText: "Edit the content to display for the current {0}, you can also customize the images on the right panel.",
      AddFormTittle: "{0} Adding Form",
      EditFormTittle: "{0} Edit Form",
      Attraction: "Attraction",
      Currency: "Currency",
      QuickNote: "A Quick Note if Needed",
      Content: "Content",
      Position: "Position",
      Lodging: "Lodging",
      CapacitySpecifics: "Capacity specifics",
      Published: "Published",
      Activated: "Activated",
      Status: "Status",
      Rating: "Rating",
      RateThis: "Rate this:",
      CurrentRate: "Current rate",
      Profile: "Profile",
      Business: "Business",
      SignOut: "Sign out",
      ForgotQuestion: "Forgot your password?",
      ForgotInstructions: "Enter your email to receive intructions on how to reset your password",
      Submit: "Submit",
      OperationSuccessful: "Operation successful",
      EmailSendInstruction: "Now check your email to receive instructions on how to reset your password",
      SuccessfulPasswordReset: "Your password has been reset successfully",
      SuccessfulPasswordResetInstructions: "You can now sign into your account",
      ResetPassword: "Reset your password",
      ResetPasswordInstructions: "Enter a new password for your {0} account.",
      NewPassword: "New password",
      ConfirmPassword: "Confirm password",
      Reset: "Reset",
      PageTittle: "Viñales Traveler",
      HomePageTittle: "The Tour Guide for Viñales's Visitors",
      HomePageDescription: "Viñales Traveler is a Tour Guide Company based in Pinar del Río, Cuba. We mostly offer ecological and sightseeing tours in Viñales and the rest of Pinar del Río province. Also a very populated catalog of Viñales’s attractions and lodgings.",
      HomePageTags: "vinales, viñales, vinales tour, viñales tour, vinales tour company, viñales tour company, ecological tour, sightseeing tours, nature, viñales lodgings, beautiful beaches,  tobacco, hiking, climbs, local food",
      ToursPageDescription: "In our tours you will get to know the natural wonders of the province of Pinar del Río, a land blessed by its peasant traditions in the cultivation of the best tobacco in the world, its beautiful beaches and incredible nature",
      ToursPageTags: "viñales tour company, ecological tour, nature, beach, landscape, tobacco, vinales, viñales, vinales tour, viñales tour, vinales tour company",
      AttractionsPageDescription: "Contact guides with mastery in several languages and specialized in hiking, horseback riding, climbing, diving and traditional dances.",
      AttractionsPageTags: "viñales tour company, ecological tour, horseback riding, hiking, climbs, dance class, restaurant, viñales, vinales tour, viñales tour, vinales tour company",
      LodgingsPageDescription: "Every lodging or rent room in Viñales has its own profile in Vinales Traveler, you can contact them from here, leave comments and rate them.",
      LodgingsPageTags: "viñales tour company, ecological tour, viñales lodgings, viñales booking, house, viñales villa, rent room, viñales, vinales tour, viñales tour, vinales tour company",
      ToursPageTittle: "Viñales Tour Catalog",
      AttractionsPageTittle: "Viñales Attractions Catalog",
      LodgingsPageTittle: "Viñales Lodgings Catalog",
      Yes: "Yes",
      Uploading: "Uploading",
      MAX_FILE_SIZE: 'You tried to exceed the maximum file size of {0}',
      UPLOAD_FAILED: "Unable to upload this specific file. Try another one."
    },
    es: {
      welcome:"Bienvenido a Viñales Traveler",
      fistp:"Una Compañía de Turismo para que disfrute su visita a Viñales al máximo.",
      secondp:"Confiables, locales y con mucha experiencia, lo guiaremos para que no se pierda de nada.",
      thirdp:"Les mostramos los mejores lugares, llenamos su estancia de maravillosas aventuras",
      button : "Descúbrelo Ahora",
      english: "Inglés",
      spanish: "Español",
      Tours: "Tours",
      Attractions: "Atracciones",
      Lodgings: "Hospedaje",
      About: "Nosotros",
      Contact: "Contacto",
      Account: "Cuenta",
      ViewOffers: "Ver Ofertas",
      ViewOffer: "Ver Oferta",
      AllLodgings: "Hospedajes",
      AboutUs: "Sobre Nosotros",
      AboutUsText: `Viñales Traveler es una empresa de turismo con sede en Pinar del Río, Cuba. Comprometidos a mostrar las bellezas y realidades de nuestra provincia desde adentro, cubriremos todos los lugares turísticos de la provincia de Pinar del Río a través de una amplia gama de recorridos ecológicos y turísticos personalizados a sitios naturales, históricos y culturales. También brindamos consejos y guías para alojamientos, restaurantes y todo tipo de actividades y atracciones, a través de nuestro catálogo de negocios turísticos de Viñales.
      <br/>Con más de diez años de experiencia en la industria del turismo como guías turísticos entre otros trabajos, nuestro personal local muy profesional ha reunido todo el conocimiento y la experiencia necesarios para cumplir con las expectativas de nuestros clientes.`,
     ContactUs: "Contáctenos",
      ContactUsText: "Viñales Traveler esta a su servicio 24/7. Siéntase libre de contactarnos por este medio, estaremos felices de atender sus solicitudes.",
      FirstName: "Nombre",
      Name: "Nombre",
      ContactEmail: "Correo de contacto",
      Subject: "Asunto",
      Message: "Mensaje",
      Send: "Enviar",
      GoForIt: "A por ellos",
      BookIt: "Reservar",
      SortBy: "Ordenar por:",    
      None: "Ninguno",  
      Filter: "Mostrar:",
      Ascending: "Ascendente",
      Descending: "Descendente",
      Comments: "Comentarios",
      Program: "Programa",
      Price: "Precio",
      Duration: "Duración",
      Languages: "Lenguajes",
      Category: "Categoría",
      Sections: "Secciones",
      Categories: "Categorias",
      Services: "Servicios",
      PickUpTime: "Recogida",
      Guide: "Guía",      
      Caracteristics: "Características",
      Capacity: "Capacidad",
      Images: "Imágenes",
      Videos: "Videos",
      Location: "Ubicación",
      AnythigElse: "Alguna otra cosa...",
      NumberOfPeople: "Número de personas",
      Date: "Fecha",
      ViewAll: "Ver todas",
      LodgingsBookingText: "Llene el siguiente formulario y evíenos los datos de su reserva de {0}. Enseguida responderemos a su solicitud.",
      SignAccount: "Iniciar sesión en su cuenta" ,
      AccountEmailAddress: "Correo de la cuenta",
      Password: "Contraseña",
      RememberMe: "Recordar",      
      ForgotPassword: "Olvidaste tu contraseña?",
      CreateAccount: "Crear una cuenta",
      LastName: "Apellido",
      EmailAddress: "Correo electrónico",
      BusinessName: "Nombre de su Negocio",
      SignUp: "Registrar",
      SignUpFacebook: "Registrar con Facebook",
      SignIn: "Iniciar Sesión",
      SignInFacebook: "Iniciar con Facebook",
      AlreadyMember: "Ya estás registrado?",
      DontAccount: "No estas registrado?",
      RepeatPassword: "Repetir contraseña",
      MyBusinesses: "Mis Negocios",
      Cancel: "Cancelar",
      ToLeaveComment: "Para calificar o dejar un comentario",
      SignInYou: "Inicie Sesión",
      FacebookLoginFailed: "Error de Inicio de sesión por Facebook",
      WrontCredentials: "Credenciales incorrectas",
      AddComment: "Añadir Comentario",
      EditComment: "Editar Comentario",
      Edit: "Editar",
      Delete: "Eliminar",
      Sending: "Enviando...",
      NewAttraction: "Nueva Atracción",
      NewLodging: "Nuevo Hospedaje",
      Add: "Adicionar",
      See: "Ver",
      Save: "Guardar",
      PriceSpecifics: "Especificaciones del precio",
      FullDescription: "Descripción completa",
      GeneralDescription: "Descripción general",
      AddFormText: "Llene el contenido a mostrar en este(a) {0}",
      EditFormText: "Edite el contenido a mostrar para este(a) {0}, puede además adicionar imágenes en el panel de la derecha",
      AddFormTittle: "Formulario Crear {0}",
      EditFormTittle: "Plantilla Editar {0}",
      Attraction: "Atracción",
      Currency: "Moneda",
      QuickNote: "Una nota, de ser necesario",
      Content: "Contenido",
      Position: "Posición",
      Lodging: "Hospedaje",
      CapacitySpecifics: "Especif capacidad",
      Published: "Publicado",
      Activated: "Activado",
      Status: "Estado",
      Rating: "Calificationes",
      RateThis: "Dale tu calificaión:",
      CurrentRate: "Calificación Actual",
      Profile: "Perfil",
      Business: "Negocios",
      SignOut: "Salir",
      ForgotQuestion: "Olvidó su contraseña?",
      ForgotInstructions: "Escriba el correo electrónico de su cuenta para recibir instrucciones de como restablecer su contraseña",
      Submit: "Enviar",
      OperationSuccessful: "Operación exitosa",
      EmailSendInstruction: "Ahora revise su correo electrónico para recibir instrucciones sobre cómo restablecer su contraseña",
      SuccessfulPasswordReset: "Su contraseña se ha restablecido correctamente",
      SuccessfulPasswordResetInstructions: "Ahora puede entrar con su cuenta",
      ResetPassword: "Restablecer conraseña",
      ResetPasswordInstructions: "Entre una nueva contraseña para su cuenta {0}.",
      NewPassword: "Nueva contraseña",
      ConfirmPassword: "Confirmar contraseña",
      Reset: "Restablecer",
      PageTittle: "Viñales Traveler",
      HomePageTittle: "Guía Turística para los Visitantes de Viñales.",
      HomePageDescription: "Viñales Traveler es una Compañia de Turismo radicada en Pinar del Río, Cuba. Ofrecemos mayormente tours de visita y ecológicos en Viñales y el resto de la provincia de Pinar del Río. Además amplio catálogo de atracciones y hospedajes en Viñales comentados y evaluados por turistas anteriores.",
      HomePageTags: "turismo, viñales, vinales tour, viñales tour, compañía de turismo, agencia de turismo, tour ecológico, naturaleza, hospedaje, playa, paseos a caballo, caminatas, escaladas, comida local",
      ToursPageDescription: "En nuestros tours conocera las maravillas naturales de toda la provincia Pinar del Río, tierra bendecida por sus tradiciones campesinas en el cultivo del mejor tabaco del mundo, sus hermosas playas y naturaleza increíble.",
      ToursPageTags: "vinales, viñales, vinales tour, viñales tour, vinales tour company, viñales tour company, turismo ecológico, naturaleza, playa, paisajes, tabaco",
      AttractionsPageDescription: "Contacte con guías con dominio en varios idiomas y especializados en senderismo, monta de caballo, escalada, Buceo y bailes tradicionales",
      AttractionsPageTags: "turismo, viñales, vinales tour, viñales turismo,  compañía de turismo, turismo ecológico,  reservar, paseos a caballo, caminatas, escaladas, comida local",
      LodgingsPageDescription: "Cada alojamiento o habitación de alquiler en Viñales tiene su propio perfil en Vinales Traveler, puede contactarlos desde aquí, dejar comentarios y calificarlos.",
      LodgingsPageTags: "turismo, compañía de turismo, turismo ecológico,, hospedaje, reservaciones, reservar, casa, habitación, viñales, viñales turismo",
      ToursPageTittle: "Catálogo de Tours",
      AttractionsPageTittle: "Catálogo de Atracciones",
      LodgingsPageTittle: "Catálogo de Hospedajes",
      Yes: "Si",
      Uploading: "Subiendo",
      MAX_FILE_SIZE: 'Esta tratando de exceder el tamaño maximo de archivo de {0}',
      UPLOAD_FAILED: "Error al intentar subir el archivo. Pruebe con otro."

    }
   }


   export default strings